micronaut:
  application:
    name: GraphQLPlaygraound
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

netty:
  default:
    allocator:
      max-order: 3

graphql:
  graphiql:
    enabled: true

endpoints:
  prometheus:
    sensitive: false