micronaut:
  application:
    name: GraphQLPlaygraound
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

netty:
  default:
    allocator:
      max-order: 3

graphql:
  graphiql:
    enabled: true
  graphql-ws:
    enabled: true
    path: /graphql-ws
    keep-alive-enabled: true
    keep-alive-interval: 15s

endpoints:
  prometheus:
    sensitive: false